[bar.default]
center = [ "control-center", "workspaces", "media" ]
end = [ "tray", "network", "bluetooth", "volume", "brightness", "battery", "sysmon", "ram", "temp", "session" ]
margin_ends = 0
position = "right"
radius = 8
radius_bottom_right = 0
radius_top_right = 0
start = [ "notifications", "wallpaper", "clock" ]
widget_spacing = 12

[calendar]

[control_center]
hidden_tabs = [ "weather" ]
sidebar = "full"
sidebar_section = "full"

    [control_center.calendar]
    show_events_card = false

    [[control_center.shortcuts]]
    type = "wifi"

    [[control_center.shortcuts]]
    type = "bluetooth"

    [[control_center.shortcuts]]
    type = "caffeine"

    [[control_center.shortcuts]]
    type = "notification"

    [[control_center.shortcuts]]
    type = "mic_mute"

    [[control_center.shortcuts]]
    type = "nightlight"

[desktop_widgets]
schema_version = 2
widget_order = []

    [desktop_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [desktop_widgets.widget]

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 300.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 600.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 360.0

[keybinds]
down = [ "Down", "Ctrl+n" ]
up = [ "Up", "Ctrl+p" ]

[lockscreen_widgets]
enabled = true
schema_version = 2
widget_order = [
    "lockscreen-login-box@HDMI-A-1",
    "lockscreen-login-box@eDP-1",
    "lockscreen-widget-0000000000000001",
    "lockscreen-widget-0000000000000002",
    "lockscreen-widget-0000000000000005",
    "lockscreen-widget-0000000000000006",
    "lockscreen-widget-0000000000000007"
]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@HDMI-A-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 960.0
    cy = 898.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000001]
    box_height = 448.0
    box_width = 576.0
    cx = 848.0
    cy = 492.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "clock"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000001.settings]
        center_text = false
        clock_style = "digital"
        format = "{:%I:%M}"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 960.0
    cy = 540.0
    output = "HDMI-A-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "calendar"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000005]
    box_height = 0.0
    box_width = 0.0
    cx = 1265.0
    cy = 490.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000005.settings]
        display = "graph"
        stat = "ram_pct"
        stat2 = "swap_pct"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000006]
    box_height = 0.0
    box_width = 0.0
    cx = 1265.0
    cy = 330.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000006.settings]
        stat = "net_rx"
        stat2 = "net_tx"

    [lockscreen_widgets.widget.lockscreen-widget-0000000000000007]
    box_height = 0.0
    box_width = 0.0
    cx = 1265.0
    cy = 650.0
    output = "eDP-1"
    placement_height = 1080.0
    placement_width = 1920.0
    rotation = 0.0
    type = "sysmon"

        [lockscreen_widgets.widget.lockscreen-widget-0000000000000007.settings]
        stat = "cpu_usage"
        stat2 = "cpu_temp"

[nightlight]
enabled = true

[plugins]
enabled = []

[shell]
avatar_path = "/home/sujan/Pictures/lockscreen/pic.jpg"
clipboard_enabled = false
polkit_agent = true
screen_time_enabled = true

    [shell.launcher]
    show_app_actions = true

    [shell.panel]
    open_near_click_control_center = true

    [shell.screenshot]
    confirm_region = true
    pipe_command = "satty -f -"
    pipe_to_command = true
    remember_last_region = true
    save_to_file = false

    [shell.session]
    grid = true
    grid_columns = 2

[theme]
builtin = "Tokyo-Night"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "qt" ]

[wallpaper]
directory = "/home/sujan/Pictures/wallpapers"

    [wallpaper.default]
    path = "/home/sujan/Pictures/wallpapers/dark-girl.jpg"

    [wallpaper.last]
    path = "/home/sujan/Pictures/wallpapers/cool_gamer_girl.jpg"

    [wallpaper.monitors.HDMI-A-1]
    path = "/home/sujan/Pictures/wallpapers/dark-girl.jpg"

    [wallpaper.monitors.eDP-1]
    path = "/home/sujan/Pictures/wallpapers/cool_gamer_girl.jpg"

[weather]
enabled = false

[widget.battery]
show_label = false

[widget.clock]
format = "{:%I:%M  %P}"
tooltip_format = "{:%A}\\n{:%Y-%m-%d}"

[widget.network]
show_label = false

[widget.ram]
show_value = false

[widget.sysmon]
show_value = false

[widget.temp]
show_value = false

[widget.workspaces]
focused_color = "on_primary"
show_labels = false
style = "focus_hint"
